INSERT INTO breed (name) VALUES ('Bulldog');
INSERT INTO breed (name) VALUES ('Labrador Retriever');
INSERT INTO breed (name) VALUES ('German Shepherd');
INSERT INTO breed (name) VALUES ('Alaskan Malamute');
INSERT INTO breed (name) VALUES ('Golden Retriever');
INSERT INTO breed (name) VALUES ('Affenpincher');
INSERT INTO breed (name) VALUES ('Airedale Terrier');
INSERT INTO breed (name) VALUES ('French Bulldog');
INSERT INTO breed (name) VALUES ('Australian Cattle Dog');
INSERT INTO breed (name) VALUES ('Poodle');
INSERT INTO breed (name) VALUES ('Afghan Hound');
INSERT INTO breed (name) VALUES ('American Eskimo Dog');
INSERT INTO breed (name) VALUES ('Beagle');
INSERT INTO breed (name) VALUES ('Australian Shepherd');
INSERT INTO breed (name) VALUES ('Chihuahua');
INSERT INTO breed (name) VALUES ('Bichon Frisé');
INSERT INTO breed (name) VALUES ('Yorkshire Terrier');
INSERT INTO breed (name) VALUES ('Border Collie');
INSERT INTO breed (name) VALUES ('American Staffordshire Terrier');
INSERT INTO breed (name) VALUES ('Anatolian Shepherd');
INSERT INTO breed (name) VALUES ('Bernese Mountain Dog');
INSERT INTO breed (name) VALUES ('Boxer');
INSERT INTO breed (name) VALUES ('Bull Terrier');
INSERT INTO breed (name) VALUES ('Cavalier King Charles Spaniel');
INSERT INTO breed (name) VALUES ('Siberian Husky');
INSERT INTO breed (name) VALUES ('Basset Hound');
INSERT INTO breed (name) VALUES ('Pug');
INSERT INTO breed (name) VALUES ('Dachshund');
INSERT INTO breed (name) VALUES ('Boston Terrier');
INSERT INTO breed (name) VALUES ('American Foxhound');
INSERT INTO breed (name) VALUES ('Newfoundland');
INSERT INTO breed (name) VALUES ('Belgian Shepherd');
INSERT INTO breed (name) VALUES ('English Cocker Spaniel');
INSERT INTO breed (name) VALUES ('Rottweiler');
INSERT INTO breed (name) VALUES ('Pomeranian');
INSERT INTO breed (name) VALUES ('Bull Mastiff');
INSERT INTO breed (name) VALUES ('Basenji');
INSERT INTO breed (name) VALUES ('Maltese');
INSERT INTO breed (name) VALUES ('Shih Tzu');
INSERT INTO breed (name) VALUES ('Havanese');
INSERT INTO breed (name) VALUES ('American Hairless Terrier');
INSERT INTO breed (name) VALUES ('Brittany');
INSERT INTO breed (name) VALUES ('Chow Chow');
INSERT INTO breed (name) VALUES ('Saint Bernard');
INSERT INTO breed (name) VALUES ('Great Dane');
INSERT INTO breed (name) VALUES ('Brussels Griffon');
INSERT INTO breed (name) VALUES ('American Water Spaniel');
INSERT INTO breed (name) VALUES ('Pekingese');
INSERT INTO breed (name) VALUES ('Boerboel');
INSERT INTO breed (name) VALUES ('Australian Terrier');
INSERT INTO breed (name) VALUES ('Papillon');
INSERT INTO breed (name) VALUES ('Cairn Terrier');
INSERT INTO breed (name) VALUES ('Silky Terrier');
